server:
  port: 8764
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: PROVIDER-TICKET

mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml
  type-aliases-package: com.ittttt.provider.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/